TRUNCATE "Member" CASCADE;
TRUNCATE "MemberProfile" CASCADE;

ALTER TABLE "MemberStatistic"
    SET UNLOGGED;
ALTER TABLE "MemberFollower"
    SET UNLOGGED;
ALTER TABLE "MemberBlogCategory"
    SET UNLOGGED;
ALTER TABLE "MemberProfile"
    SET UNLOGGED;
ALTER TABLE "Member"
    SET UNLOGGED;