ALTER TABLE "BlogReact"
DROP
CONSTRAINT IF EXISTS "PK_BlogReact";

ALTER TABLE "BlogReact"
DROP
CONSTRAINT IF EXISTS "FK_BlogReact_Blog_Id";

TRUNCATE "BlogReact";

ALTER TABLE "BlogReact" SET UNLOGGED;